import { FileProps } from "./interfaces";

export const files: FileProps[] = [
  {
    id: 1,
    name: "file1.txt",
    mimetype: "text/plain",
    size: 1024,
    url: "https://example.com/file1.txt",
    uploaded: new Date("2023-06-01"),
  },
  {
    id: 2,
    name: "image.jpg",
    mimetype: "image/jpeg",
    size: 2048,
    url: "https://example.com/image.jpg",
    uploaded: new Date("2023-06-02"),
  },
  {
    id: 3,
    name: "document.pdf",
    mimetype: "application/pdf",
    size: 4096,
    url: "https://example.com/document.pdf",
    uploaded: new Date("2023-06-03"),
  },
  {
    id: 4,
    name: "video.mp4",
    mimetype: "video/mp4",
    size: 8192,
    url: "https://example.com/video.mp4",
    uploaded: new Date("2023-06-04"),
  },
  {
    id: 5,
    name: "presentation.pptx",
    mimetype:
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    size: 16384,
    url: "https://example.com/presentation.pptx",
    uploaded: new Date("2023-06-05"),
  },
  {
    id: 6,
    name: "audio.mp3",
    mimetype: "audio/mpeg",
    size: 32768,
    url: "https://example.com/audio.mp3",
    uploaded: new Date("2023-06-06"),
  },
  {
    id: 7,
    name: "spreadsheet.xlsx",
    mimetype:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    size: 65536,
    url: "https://example.com/spreadsheet.xlsx",
    uploaded: new Date("2023-06-07"),
  },
  {
    id: 8,
    name: "code.js",
    mimetype: "application/javascript",
    size: 131072,
    url: "https://example.com/code.js",
    uploaded: new Date("2023-06-08"),
  },
  {
    id: 9,
    name: "image2.png",
    mimetype: "image/png",
    size: 262144,
    url: "https://example.com/image2.png",
    uploaded: new Date("2023-06-09"),
  },
  {
    id: 10,
    name: "document2.pdf",
    mimetype: "application/pdf",
    size: 524288,
    url: "https://example.com/document2.pdf",
    uploaded: new Date("2023-06-10"),
  },
  {
    id: 11,
    name: "file2.txt",
    mimetype: "text/plain",
    size: 1048576,
    url: "https://example.com/file2.txt",
    uploaded: new Date("2023-06-11"),
  },
  {
    id: 12,
    name: "image3.jpg",
    mimetype: "image/jpeg",
    size: 2097152,
    url: "https://example.com/image3.jpg",
    uploaded: new Date("2023-06-12"),
  },
  {
    id: 13,
    name: "document3.pdf",
    mimetype: "application/pdf",
    size: 4194304,
    url: "https://example.com/document3.pdf",
    uploaded: new Date("2023-06-13"),
  },
  {
    id: 14,
    name: "video2.mp4",
    mimetype: "video/mp4",
    size: 8388608,
    url: "https://example.com/video2.mp4",
    uploaded: new Date("2023-06-14"),
  },
  {
    id: 15,
    name: "presentation2.pptx",
    mimetype:
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    size: 16777216,
    url: "https://example.com/presentation2.pptx",
    uploaded: new Date("2023-06-15"),
  },
  {
    id: 16,
    name: "presentation2.pptx",
    mimetype:
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    size: 16777216,
    url: "https://example.com/presentation2.pptx",
    uploaded: new Date("2023-06-15"),
  },
  {
    id: 17,
    name: "presentation2.pptx",
    mimetype:
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    size: 16777216,
    url: "https://example.com/presentation2.pptx",
    uploaded: new Date("2023-06-15"),
  },
  {
    id: 18,
    name: "presentation2.pptx",
    mimetype:
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    size: 16777216,
    url: "https://example.com/presentation2.pptx",
    uploaded: new Date("2023-06-15"),
  },
  {
    id: 19,
    name: "presentation2.pptx",
    mimetype:
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    size: 16777216,
    url: "https://example.com/presentation2.pptx",
    uploaded: new Date("2023-06-15"),
  },
  {
    id: 20,
    name: "presentation2.pptx",
    mimetype:
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    size: 16777216,
    url: "https://example.com/presentation2.pptx",
    uploaded: new Date("2023-06-15"),
  },
];
